import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface Skill {
  slug: string;
  title: string;
  description: string;
  category: string;
  type: 'skill' | 'agent';
}

const REPO = 'urmzd/dotfiles';
const SKILLS_PATH = 'dot_agents/skills';
const AGENTS_PATH = 'dot_agents/agents';

function parseFrontmatter(content: string): Record<string, string> {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fields: Record<string, string> = {};
  let currentKey = '';
  let currentValue = '';
  for (const line of match[1].split('\n')) {
    const kvMatch = line.match(/^(\w[\w-]*):\s*(.*)/);
    if (kvMatch) {
      if (currentKey) fields[currentKey] = currentValue.trim();
      currentKey = kvMatch[1];
      currentValue = kvMatch[2].replace(/^>\s*$/, '');
    } else if (currentKey && line.match(/^\s+/)) {
      currentValue += ' ' + line.trim();
    }
  }
  if (currentKey) fields[currentKey] = currentValue.trim();
  return fields;
}

function parseMetadata(content: string): { title?: string; category?: string } {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const metaMatch = match[1].match(/metadata:\s*\n((?:\s{2,}\w[\s\S]*?)?)(?=\n\w|$)/);
  if (!metaMatch) return {};
  const title = metaMatch[1].match(/title:\s*(.+)/)?.[1]?.trim();
  const category = metaMatch[1].match(/category:\s*(.+)/)?.[1]?.trim();
  return { title, category };
}

function stripFrontmatter(content: string): string {
  return content.replace(/^---\n[\s\S]*?\n---\n*/, '');
}

function main() {
  console.log('Fetching skills from', REPO);

  const listing = execSync(`gh api repos/${REPO}/contents/${SKILLS_PATH} --jq '.[].name'`, {
    encoding: 'utf-8',
  }).trim();
  const skillDirs = listing.split('\n').filter(Boolean);

  const skills: Skill[] = [];
  const contentDir = join(import.meta.dirname, '..', 'src', 'skills');
  mkdirSync(contentDir, { recursive: true });

  for (const dir of skillDirs) {
    try {
      const encoded = execSync(
        `gh api repos/${REPO}/contents/${SKILLS_PATH}/${dir}/SKILL.md --jq '.content'`,
        { encoding: 'utf-8' },
      ).trim();
      const raw = Buffer.from(encoded, 'base64').toString('utf-8');
      const fm = parseFrontmatter(raw);
      const meta = parseMetadata(raw);
      const body = stripFrontmatter(raw);

      const title = meta.title || fm.name || dir;
      const description = fm.description || '';
      const category = meta.category || 'general';

      // Write markdown content file for Astro collection
      const mdFrontmatter = [
        '---',
        `title: "${title.replace(/"/g, '\\"')}"`,
        `description: "${description.replace(/"/g, '\\"')}"`,
        `category: "${category}"`,
        '---',
      ].join('\n');
      writeFileSync(join(contentDir, `${dir}.md`), `${mdFrontmatter}\n\n${body}`);

      skills.push({ slug: dir, title, description, category, type: 'skill' });
    } catch {
      console.warn(`Skipping ${dir}: could not fetch SKILL.md`);
    }
  }

  // Fetch agents
  console.log('Fetching agents from', REPO);
  const agentListing = execSync(`gh api repos/${REPO}/contents/${AGENTS_PATH} --jq '.[].name'`, {
    encoding: 'utf-8',
  }).trim();
  const agentFiles = agentListing.split('\n').filter((f) => f.endsWith('.md'));

  for (const file of agentFiles) {
    try {
      const encoded = execSync(
        `gh api repos/${REPO}/contents/${AGENTS_PATH}/${file} --jq '.content'`,
        { encoding: 'utf-8' },
      ).trim();
      const raw = Buffer.from(encoded, 'base64').toString('utf-8');
      const fm = parseFrontmatter(raw);
      const body = stripFrontmatter(raw);

      const slug = file.replace(/\.md$/, '');
      const title = fm.name || slug;
      const description = fm.description || '';

      const mdFrontmatter = [
        '---',
        `title: "${title.replace(/"/g, '\\"')}"`,
        `description: "${description.replace(/"/g, '\\"')}"`,
        `category: "agent"`,
        '---',
      ].join('\n');
      writeFileSync(join(contentDir, `${slug}.md`), `${mdFrontmatter}\n\n${body}`);

      skills.push({ slug, title, description, category: 'agent', type: 'agent' });
    } catch {
      console.warn(`Skipping agent ${file}: could not fetch`);
    }
  }

  skills.sort((a, b) => a.category.localeCompare(b.category) || a.title.localeCompare(b.title));

  const output = `// Auto-generated by scripts/fetch-skills.ts — do not edit manually
export interface Skill {
  slug: string;
  title: string;
  description: string;
  category: string;
  type: 'skill' | 'agent';
}

export const skills: Skill[] = ${JSON.stringify(skills, null, 2)};

const categoryLabels: Record<string, string> = {
  ai: 'AI & Agents',
  cli: 'CLI & DevEnv',
  development: 'Development',
  security: 'Security',
  visual: 'Visual & Branding',
  agent: 'Agents',
  general: 'General',
};

export function getCategoryLabel(category: string): string {
  return categoryLabels[category] || category.charAt(0).toUpperCase() + category.slice(1);
}

export const categories = [...new Set(skills.map((s) => s.category))];
`;

  const outPath = join(import.meta.dirname, '..', 'src', 'data', 'skills.ts');
  writeFileSync(outPath, output);
  console.log(`Wrote ${skills.length} skills (+ markdown files) to src/data/skills.ts`);
}

main();
