// Auto-generated by scripts/fetch-skills.ts — do not edit manually
export interface Skill {
  slug: string;
  title: string;
  description: string;
  category: string;
}

export const skills: Skill[] = [
  {
    slug: 'configure-ai',
    title: 'AI Workflows',
    description:
      'AI tools, Claude Code configuration, sr commits, AGENTS.md standard, skills-as-docs philosophy, and llms.txt. Use when setting up AI tooling, configuring projects for AI, or working with agent skills.',
    category: 'ai',
  },
  {
    slug: 'create-llms-txt',
    title: 'Create llms.txt',
    description:
      'Generate a spec-compliant llms.txt file for any project by analyzing its codebase, docs, and public URLs. Use when creating an llms.txt, making a project LLM-discoverable, or when the user mentions "llms.txt" in the context of generating or scaffolding one.',
    category: 'ai',
  },
  {
    slug: 'create-oss-skill',
    title: 'Create OSS Skill',
    description:
      'Create well-formed Agent Skills following the agentskills.io specification — scaffold directories, write SKILL.md files, bundle scripts, and structure instructions for progressive disclosure. Use when creating a new skill, reviewing skill structure, optimizing a skill description, or setting up evals for skill quality.',
    category: 'ai',
  },
  {
    slug: 'extend-oss-skills-to-claude',
    title: 'Extend OSS Skills to Claude',
    description:
      'Extend standard agentskills.io skills with Claude Code-specific features — invocation control, subagent execution, dynamic context injection, string substitutions, model/effort overrides, and deployment scoping. Use when adapting a portable skill for Claude Code, adding Claude-specific frontmatter, setting up subagent delegation, or configuring skill permissions.',
    category: 'ai',
  },
  {
    slug: 'setup-devenv',
    title: 'Nix Dev Shells',
    description:
      '13 composable Nix development shells for reproducible tooling. Use when setting up dev environments, configuring .envrc files, or adding Nix shells to projects.',
    category: 'cli',
  },
  {
    slug: 'setup-ci',
    title: 'CI/CD Standards',
    description:
      'CI/CD conventions — ci.yml + release.yml naming, concurrency, bot skip, embed-src/teasr steps, and workflow structure. Language-specific pipelines live in scaffold-rust, scaffold-go, scaffold-python, scaffold-node, scaffold-terraform. Use when setting up GitHub Actions or understanding CI conventions.',
    category: 'development',
  },
  {
    slug: 'build-cli',
    title: 'CLI Patterns',
    description:
      'CLI conventions — output modes, TTY detection, JSON piping, stdout/stderr separation, interactivity, signal handling, visual style, and CI integration. Use when building or reviewing any CLI tool.',
    category: 'development',
  },
  {
    slug: 'assess-quality',
    title: 'Code Quality',
    description:
      'Code quality assessment — readability, onboarding ease, scalability without bloat, brand coherence across projects, and intentional design for developers and AI agents. The foundational "why" behind all conventions. Use when reviewing code quality, assessing project health, onboarding to a new project, or making architectural decisions about structure and consistency.',
    category: 'development',
  },
  {
    slug: 'write-code',
    title: 'Development Practices',
    description:
      'Tech stack, coding patterns, commit conventions, interface design, error handling, testing, and junior-friendly philosophy. Use when writing code, making commits, or choosing tools/patterns.',
    category: 'development',
  },
  {
    slug: 'review-design',
    title: 'Pragmatic Programming',
    description:
      'Pragmatic Programmer principles — DRY, orthogonality, tracer bullets, prototyping, estimation, design by contract, and pragmatic paranoia. Use when writing, reviewing, or refactoring code.',
    category: 'development',
  },
  {
    slug: 'scaffold-project',
    title: 'Project Scaffolding',
    description:
      'Project structure — standard files, documentation conventions, and dispatch to language-specific scaffolds. Use when creating or standardizing projects. Delegates to scaffold-rust, scaffold-go, scaffold-python, scaffold-node, or scaffold-terraform for CI/CD, release pipelines, and language-specific config.',
    category: 'development',
  },
  {
    slug: 'setup-release',
    title: 'Release Workflow',
    description:
      'Release pipeline conventions — sr.yaml config, sr action usage, git hooks, monorepo support, post-release patterns, and version file mapping. Language-specific build targets and publishing live in scaffold-rust, scaffold-go, scaffold-python, scaffold-node. Use when setting up or modifying release pipelines.',
    category: 'development',
  },
  {
    slug: 'scaffold-go',
    title: 'Scaffold Go Project',
    description:
      'Scaffold a complete Go project with CI/CD, release pipeline, justfile, sr.yaml, .envrc, and standard files. Use when creating a new Go CLI, service, or module, or when the user mentions "new Go project", "go mod init", or "Go scaffold".',
    category: 'development',
  },
  {
    slug: 'scaffold-node',
    title: 'Scaffold Node/TypeScript Project',
    description:
      'Scaffold a complete Node/TypeScript project with CI/CD, release pipeline, justfile, sr.yaml, .envrc, and standard files. Uses npm and biome. Use when creating a new Node.js app, TypeScript library, or website, or when the user mentions "new Node project", "npm init", "TypeScript scaffold", or "Astro site".',
    category: 'development',
  },
  {
    slug: 'scaffold-python',
    title: 'Scaffold Python Project',
    description:
      'Scaffold a complete Python project with CI/CD, release pipeline, justfile, sr.yaml, pyproject.toml, .envrc, and standard files. Uses uv and ruff. Use when creating a new Python CLI, library, or application, or when the user mentions "new Python project", "uv init", or "Python scaffold".',
    category: 'development',
  },
  {
    slug: 'scaffold-rust',
    title: 'Scaffold Rust Project',
    description:
      'Scaffold a complete Rust project with CI/CD, release pipeline, justfile, sr.yaml, .envrc, and standard files. Use when creating a new Rust CLI, library, or workspace, or when the user mentions "new Rust project", "cargo init", or "Rust scaffold".',
    category: 'development',
  },
  {
    slug: 'scaffold-terraform',
    title: 'Scaffold Terraform Project',
    description:
      'Scaffold a Terraform infrastructure project with CI/CD (plan on PR, apply on push), AWS OIDC auth, justfile, .envrc, and standard files. Use when creating infrastructure repos, or when the user mentions "new Terraform project", "terraform init", "AWS infra", or "infrastructure scaffold".',
    category: 'development',
  },
  {
    slug: 'test-code',
    title: 'Testing Practices',
    description:
      'Testing philosophy, test types, per-language conventions, file organization, fixtures/mocks, CI strategy, and what NOT to test. Use when writing tests, reviewing test coverage, setting up test infrastructure, or deciding what to test.',
    category: 'development',
  },
  {
    slug: 'choose-stack',
    title: 'Tools',
    description:
      'Canonical tech stack reference organized by purpose — release, docs/demos, codegen, and per-language tools. Use when choosing libraries, setting up projects, or selecting the right tool.',
    category: 'development',
  },
  {
    slug: 'audit-security',
    title: 'Security Audit',
    description:
      'Security auditing, threat detection, sensitive data leak prevention, and system diagnostics via Activity Monitor. Use when checking for security issues, investigating suspicious processes, preventing credential leaks, or hardening configurations.',
    category: 'security',
  },
  {
    slug: 'write-readme',
    title: 'README Standards',
    description:
      'README structure — centered header, badges, demos, section order, Agent Skill section, and llms.txt. Use when creating or updating any project README.',
    category: 'visual',
  },
  {
    slug: 'style-brand',
    title: 'Visual Identity',
    description:
      'Terminal theme, font, VHS demos, teasr integration, asset conventions, and branding across README/demos. Use when configuring appearance, recording demos, or maintaining visual consistency.',
    category: 'visual',
  },
];

const categoryLabels: Record<string, string> = {
  ai: 'AI & Agents',
  cli: 'CLI & DevEnv',
  development: 'Development',
  security: 'Security',
  visual: 'Visual & Branding',
  general: 'General',
};

export function getCategoryLabel(category: string): string {
  return categoryLabels[category] || category.charAt(0).toUpperCase() + category.slice(1);
}

export const categories = [...new Set(skills.map((s) => s.category))];
